name: victoria_game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  get: 4.6.5
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIconData
      fonts:
        - asset: assets/fonts/CustomIconData.ttf
